apiVersion: v1
kind: deployment
metadata:
  name: LocationStatusAPI
  labels:
    app: LocationStatusAPI
    tier: webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: LocationStatusAPI
        tier: webserver
    spec:
      containers:
        - name: LocationStatusAPI
          image: LocationStatusAPI:latest
          imagePullPolicy: Always