apiVersion: v1
kind: deployment
metadata:
  name: location-status-api
  labels:
    app: location-status-api
    tier: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-status-api
  template:
    metadata:
      labels:
        app: location-status-api
        tier: webserver
    spec:
      containers:
        - name: location-status-api
          image: LocationStatusAPI:latest
          imagePullPolicy: Always