piVersion: v1
kind: deployment
metadata:
  name: LocationSearchAPI
  labels:
    app: LocationSearchAPI
    tier: webserver
spec:
  replicas: 1
  selector:
    matchlabels:
      tier: webserver
    template:
      metadata:
        labels:
          app: LocationSearchAPI
          tier: webserver
      spec:
        containers:
          - name: LocationSearchAPI
            image: ./LocationSearchAPI/target/LocationSearchAPI.jar
            ports:
              - containerPort: 7000
            imagePullPolicy: Always